# Generated by Django 3.2.7 on 2021-10-04 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Показывать?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 10, 4), verbose_name='Дата конца паказа(включая)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='freq',
            field=models.CharField(choices=[('VERY_HIGH', 'Очень часто'), ('HIGH', 'Часто'), ('MID', 'Средне'), ('LOW', 'Редко'), ('VERY_LOW', 'Очень редко')], default='MID', max_length=9, verbose_name='Частота показа'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 10, 4), verbose_name='Дата начала показа (включая)'),
        ),
    ]
