# Generated by Django 3.2.7 on 2021-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20211004_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text_after',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Текст под картинкой (128 символов максимум)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text_before',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Текст над картинкой (256 символов максимум)'),
        ),
    ]
