# Generated by Django 3.2.7 on 2021-10-04 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_auto_20211004_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='text_after',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Текст под картинкой (64 символа максимум)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='text_before',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Текст над картинкой (128 символов максимум)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='Дата конца паказа(включая)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='Дата начала показа (включая)'),
        ),
    ]
