# Generated by Django 3.2.7 on 2024-12-18 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20241218_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала показа (включая)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата конца показа (включая)'),
        ),

    ]
