# Generated by Django 3.2.7 on 2024-12-18 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20241218_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Дата конца паказа(включая)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 12, 18), verbose_name='Дата начала показа (включая)'),
        ),
    ]
