# Generated by Django 3.2.7 on 2024-12-18 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0008_alter_video_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 11, 53, 59, 682530, tzinfo=utc), verbose_name='Дата конца паказа(включая)'),
        ),
    ]
